/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/
#include<stdio.h>

int main()
{int i;
long int num=0,num1=1,num2=2,sum=2;	//num2=(nth term -1) & num1 = (nth term-2)
for(i=3;num<4000000;i++)
{num=num1+num2;
num1=num2;
num2=num;
if(num%2==0)
sum=sum+num;
}
printf ("The required sum is %ld\n", sum);
} 
